# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
    pre_install:
      - /home/docs/.local/bin/uv export --only-group docs --format requirements.txt -o docs-requirements.txt

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
