language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements-travis.txt
script:
  - python setup.py build
  - python setup.py install
  - python tests/test_sacio.py
  - py.test -v --mpl tests/test_sacfunc.py
