site_name: pysmo
copyright: Copyright &copy; 2012 - 2025 Simon Lloyd

# Repository
repo_name: pysmo/pysmo
repo_url: https://github.com/pysmo/pysmo

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      ignore:
        - docs/gen_ref_pages.py
        - docs/snippets/*.py
  # - gen-files:
  #     scripts:
  #       - docs/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - termynal:
      prompt_literal_start:
        - "$"
        - ">>>"
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
          import:
            - https://docs.python.org/3/objects.inv
            - https://mypy.readthedocs.io/en/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://pip.pypa.io/en/stable/objects.inv
            - https://docs.pytest.org/en/stable/objects.inv
            - https://pytest-mpl.readthedocs.io/en/latest/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://flake8.pycqa.org/en/latest/objects.inv
            - https://www.mkdocs.org/objects.inv
            - https://pyproj4.github.io/pyproj/stable/objects.inv

nav:
  - Home:
      - pysmo: index.md
  - First Steps:
      - first-steps/index.md
      - first-steps/installation.md
      - first-steps/tutorial.ipynb
  - User Guide:
      - user-guide/index.md
      - user-guide/in-the-box.md
      - user-guide/types.md
      - user-guide/classes.md
      - user-guide/functions.md
  - API Reference:
      - pysmo: reference/base.md
      - pysmo.functions: reference/functions.md
      - pysmo.classes: reference/classes.md
      - pysmo.tools.noise: reference/tools/noise.md
      - pysmo.tools.signal: reference/tools/signal.md
      - pysmo._io: reference/_io.md
  - Gallery:
      - gallery/index.md
  - Developing pysmo:
      - developing/index.md
      - developing/developing.md
      - developing/contributing.md
  - contributors.md
  - changelog.md
