site_name: pysmo
copyright: Copyright &copy; 2012 - 2025 Simon Lloyd

# Repository
repo_name: pysmo/pysmo
repo_url: https://github.com/pysmo/pysmo

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - css/material.css
  - css/mermaid.css
  - css/mkdocstrings.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  version:
    provider: mike

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight:
      default_lang: python
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - autorefs
  - bibtex:
      bib_file: docs/refs.bib
  - mkdocs-jupyter:
      ignore:
        - docs/gen_ref_pages.py
        - docs/snippets/*.py
        - docs/first-steps/tutorial/*.py
  # - gen-files:
  #     scripts:
  #       - docs/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - termynal:
      prompt_literal_start:
        - "$"
        - ">>>"
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            backlinks: tree
            docstring_section_style: list
            docstring_style: google
            # extensions:
            #   - griffe_fieldz
            # force_inspection: true
            inherited_members: true
            modernize_annotations: true
            parameter_headings: false
            separate_signature: true
            # show_if_no_docstring: false
            show_inheritance_diagram: true
            show_overloads: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            # with_preloaded_modules: true
            extra:
              trim_doctest_flags: true
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://mypy.readthedocs.io/en/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://pip.pypa.io/en/stable/objects.inv
            - https://docs.pytest.org/en/stable/objects.inv
            - https://pytest-mpl.readthedocs.io/en/latest/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://flake8.pycqa.org/en/latest/objects.inv
            - https://www.mkdocs.org/objects.inv
            - https://pyproj4.github.io/pyproj/stable/objects.inv
            - https://attrs.org/en/stable/objects.inv
            - https://attrs-strict.readthedocs.io/en/stable/objects.inv

nav:
  - Home:
      - pysmo: index.md
  - First Steps:
      - first-steps/index.md
      - first-steps/installation.md
      - first-steps/tutorial/tutorial.ipynb
  - User Guide:
      - user-guide/index.md
      - user-guide/in-the-box.md
      - user-guide/types.md
      - user-guide/classes.md
      - user-guide/functions.md
  - API Reference:
      - pysmo:
          - api/index.md
      - pysmo.classes:
          - api/pysmo/classes/index.md
      - pysmo.functions:
          - api/pysmo/functions/index.md
      - pysmo.tools:
          - api/pysmo/tools/index.md
          - azdist: api/pysmo/tools/azdist.md
          - iccs: api/pysmo/tools/iccs.md
          - noise: api/pysmo/tools/noise.md
          - plotutils: api/pysmo/tools/plotutils.md
          - signal: api/pysmo/tools/signal.md
          - utils: api/pysmo/tools/utils.md
      - pysmo.lib:
          - api/pysmo/lib/index.md
  - Developing pysmo:
      - developing/index.md
      - developing/developing.md
      - developing/contributing.md
  - contributors.md
  - changelog.md

exclude_docs: |
  conftest.py
  examples/tools/noise/*.py
  examples/tools/iccs/*.py
