"""One-off generator for `mseed_gap.mseed`.

Run from the repository root with `uv run python
tests/classes/assets/generate_mseed_gap.py`. The output is committed as a
binary fixture and is not regenerated by the test suite.

Produces two contiguous segments under one FDSN Source Identifier,
separated by a data gap: `MSeed.all_from_file` yields two segments and
`MSeed.from_file` raises `ValueError`.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from pymseed import DataEncoding, MS3TraceList

SOURCEID = "FDSN:IU_ANMO_00_B_H_Z"
SAMPLE_RATE_HZ = 20.0

# 200 samples at 20 Hz (10 s), a 60 s gap, then another 200 samples.
START_1 = pd.Timestamp("2010-02-27T06:44:00Z").value
START_2 = pd.Timestamp("2010-02-27T06:45:10Z").value


def main() -> None:
    tracelist = MS3TraceList()
    for start, sample_range in ((START_1, (0, 200)), (START_2, (200, 400))):
        tracelist.add_data(
            sourceid=SOURCEID,
            data_samples=np.arange(*sample_range, dtype=np.int32),
            sample_type="i",
            sample_rate=SAMPLE_RATE_HZ,
            starttime=start,
            publication_version=1,
        )
    out = Path(__file__).parent / "mseed_gap.mseed"
    tracelist.to_file(out, overwrite=True, encoding=DataEncoding.STEIM2)


if __name__ == "__main__":
    main()
