#!/usr/bin/env python3
"""
Generate PEP 695 Literal type aliases from Enum/StrEnum classes.

Example:
    $ python tools/gen_literals.py \
        --modules myproj.types myproj.more_types \
        --out src/myproj/types_generated.py

Features:
- Scans specified modules (and their submodules if you pass --recursive)
- Selectively include/exclude enums by name or regex
- Only emits aliases for enums with *all string* or *all int* values
- Deterministic ordering; writes a single file with __all__
- Optional alias prefix/suffix (e.g., Mode -> ModeLiteral)

Python: 3.12+
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import pkgutil
import re
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from types import ModuleType
from typing import Iterable, Iterator, Literal, Sequence

# --- Configurable header written at the top of the generated file ---
HEADER = """# AUTOGENERATED FILE. DO NOT EDIT.
# Regenerate with: python tools/gen_literals.py {cli}
from __future__ import annotations
from typing import Literal

"""

# ---------- Data model ----------


@dataclass(frozen=True)
class EnumSpec:
    module: str  # module where the enum is defined
    qualname: str  # qualified name within module
    enum_name: str  # class name, e.g., Mode
    alias_name: str  # PEP 695 alias, e.g., ModeLiteral
    kind: Literal["str", "int"]
    values: tuple[str | int, ...]  # sorted, unique


# ---------- Discovery ----------


def iter_modules(root: ModuleType, recursive: bool) -> Iterator[ModuleType]:
    """Yield root module and optionally its submodules (importing them)."""
    yield root
    if not recursive or not hasattr(root, "__path__"):
        return
    for modinfo in pkgutil.walk_packages(root.__path__, prefix=root.__name__ + "."):  # type: ignore[arg-type]
        try:
            yield importlib.import_module(modinfo.name)
        except Exception as e:
            print(
                f"[warn] Skipping submodule import {modinfo.name}: {e}", file=sys.stderr
            )


def discover_enums(
    module_names: Sequence[str],
    recursive: bool,
    include: Sequence[str],
    include_regex: Sequence[str],
    exclude: Sequence[str],
    exclude_regex: Sequence[str],
) -> list[tuple[ModuleType, type[Enum]]]:
    """Find Enum classes in given modules that match filters."""
    inc_set = set(include)
    exc_set = set(exclude)
    inc_re = [re.compile(r) for r in include_regex]
    exc_re = [re.compile(r) for r in exclude_regex]

    found: list[tuple[ModuleType, type[Enum]]] = []
    for modname in module_names:
        try:
            root = importlib.import_module(modname)
        except Exception as e:
            print(f"[warn] Cannot import module {modname}: {e}", file=sys.stderr)
            continue

        for mod in iter_modules(root, recursive=recursive):
            for name, obj in vars(mod).items():
                if not inspect.isclass(obj):
                    continue
                if not issubclass(obj, Enum):
                    continue
                if obj.__module__ != mod.__name__:
                    # skip re-exports; only define where declared
                    continue

                # Filtering
                if inc_set and name not in inc_set:
                    # If explicit include list supplied, skip non-members
                    continue
                if any(r.search(name) for r in inc_re) is False and inc_re:
                    # Include regex provided but didn't match
                    continue
                if name in exc_set:
                    continue
                if any(r.search(name) for r in exc_re):
                    continue

                found.append((mod, obj))  # type: ignore[arg-type]
    return found


# ---------- Processing ----------


def enum_values_kind(
    e: type[Enum],
) -> tuple[Literal["str", "int"] | None, tuple[str | int, ...]]:
    """Return ('str' or 'int', values) if all values are strings or ints; else (None, ...)."""
    vals = tuple(member.value for member in e)  # type: ignore[attr-defined]
    if all(isinstance(v, str) for v in vals):
        # De-duplicate (safety) and sort
        uniq = tuple(sorted({str(v) for v in vals}))
        return "str", uniq
    if all(isinstance(v, int) and not isinstance(v, bool) for v in vals):
        uniq = tuple(sorted({int(v) for v in vals}))
        return "int", uniq
    return None, vals  # unsupported mix or non-primitive values


def make_alias_name(
    enum_name: str, prefix: str | None, suffix: str | None, rename: dict[str, str]
) -> str:
    if enum_name in rename:
        return rename[enum_name]
    base = enum_name
    if prefix:
        base = f"{prefix}{base}"
    if suffix:
        base = f"{base}{suffix}"
    return base


def build_specs(
    pairs: Iterable[tuple[ModuleType, type[Enum]]],
    prefix: str | None,
    suffix: str | None,
    rename: dict[str, str],
) -> list[EnumSpec]:
    specs: list[EnumSpec] = []
    for mod, cls in pairs:
        kind, vals = enum_values_kind(cls)
        if kind is None:
            print(
                f"[info] Skipping {mod.__name__}.{cls.__name__}: values not all str or int",
                file=sys.stderr,
            )
            continue
        alias = make_alias_name(cls.__name__, prefix, suffix, rename)
        specs.append(
            EnumSpec(
                module=mod.__name__,
                qualname=cls.__qualname__,
                enum_name=cls.__name__,
                alias_name=alias,
                kind=kind,
                values=vals,
            )
        )
    # Deterministic ordering: by module then enum name
    specs.sort(key=lambda s: (s.module, s.enum_name))
    return specs


# ---------- Emission ----------


def literal_line(spec: EnumSpec) -> str:
    items = ", ".join(f'"{v}"' if spec.kind == "str" else f"{v}" for v in spec.values)
    return f"type {spec.alias_name} = Literal[{items}]\n"


def emit(specs: Sequence[EnumSpec], out_path: Path, cli_args: str) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append(HEADER.format(cli=cli_args))
    # Helpful comment mapping enum -> alias
    for s in specs:
        lines.append(f"# {s.module}.{s.enum_name} -> {s.alias_name}\n")
    lines.append("\n")

    # Aliases
    for s in specs:
        lines.append(literal_line(s))
    lines.append("\n")

    # __all__
    all_names = ", ".join(f'"{s.alias_name}"' for s in specs)
    lines.append(f"__all__ = [{all_names}]\n")

    new_text = "".join(lines)
    old_text = out_path.read_text(encoding="utf-8") if out_path.exists() else None
    if old_text == new_text:
        print(f"[ok] {out_path} is up-to-date")
        return
    out_path.write_text(new_text, encoding="utf-8")
    print(f"[write] {out_path} ({len(specs)} alias(es))")


# ---------- CLI ----------


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--modules",
        nargs="+",
        required=True,
        help="Top-level modules/packages to scan (e.g. myproj.types myproj.models)",
    )
    p.add_argument(
        "--recursive",
        action="store_true",
        help="Walk submodules of each package",
    )
    p.add_argument(
        "--include",
        nargs="*",
        default=[],
        help="Exact enum class names to include (if provided, acts as allowlist)",
    )
    p.add_argument(
        "--include-regex",
        nargs="*",
        default=[],
        help="Regex patterns for enum class names to include",
    )
    p.add_argument(
        "--exclude",
        nargs="*",
        default=[],
        help="Exact enum class names to exclude",
    )
    p.add_argument(
        "--exclude-regex",
        nargs="*",
        default=[],
        help="Regex patterns for enum class names to exclude",
    )
    p.add_argument(
        "--alias-prefix",
        default="",
        help='Optional alias prefix (default: "")',
    )
    p.add_argument(
        "--alias-suffix",
        default="Literal",
        help='Optional alias suffix (default: "Literal")',
    )
    p.add_argument(
        "--rename",
        nargs="*",
        default=[],
        help="Rename mappings like EnumName=AliasName (repeatable or space-separated)",
    )
    p.add_argument(
        "--out",
        required=True,
        help="Output file path for generated aliases (e.g. src/myproj/types_generated.py)",
    )
    p.add_argument(
        "--src-root",
        default="src",
        help="Add this path to sys.path first (default: src). Use '.' if not needed.",
    )
    return p.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    ns = parse_args(sys.argv[1:] if argv is None else argv)

    # Make imports resolve your package
    if ns.src_root:
        sys.path.insert(0, str(Path(ns.src_root).resolve()))

    rename_map: dict[str, str] = {}
    for item in ns.rename:
        if "=" not in item:
            print(f"[warn] --rename expects Enum=Alias, got {item!r}", file=sys.stderr)
            continue
        enum_name, alias_name = item.split("=", 1)
        rename_map[enum_name] = alias_name

    pairs = discover_enums(
        module_names=ns.modules,
        recursive=ns.recursive,
        include=ns.include,
        include_regex=ns.include_regex,
        exclude=ns.exclude,
        exclude_regex=ns.exclude_regex,
    )
    specs = build_specs(
        pairs,
        prefix=ns.alias_prefix or None,
        suffix=ns.alias_suffix or None,
        rename=rename_map,
    )

    cli = " ".join(map(str, sys.argv[1:]))
    emit(specs, Path(ns.out), cli_args=cli)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
