name: unit tests

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Set up environment with poetry
        run: |
          poetry install
      - name: Lint with flake8
        run: |
          make lint
      - name: Test with pytest
        run: |
          make tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        if: ${{ matrix.python-version == '3.11' }}
